### ISSUE TITLE
Input validation in separated file

### ISSUE THREAD

**Issue by mehdihadeli** [mehdihadeli/go-ecommerce-microservices#7]
Currently, I use tags for validating inputs with [go-playground/validator](https://github.com/go-playground/validator) package, maybe it's cleaner that we move them to `validator.go` file in each slice.
- [https://github.com/go-ozzo/ozzo-validation](https://github.com/go-ozzo/ozzo-validation)
- [Input validation in GoLang](https://medium.com/@apzuk3/input-validation-in-golang-bc24cdec1835)

**Comment by Alan-MQ** [comment]
u mean use custom validator.go file to replace all the validator package right?  
btw, I'm new to this project and really interested to help, do you think this issue is great for me to start contribute?

**Comment by mehdihadeli** [comment]
Maybe we could put it in same command file and replacing `validate` attribute and [validator](https://github.com/go-playground/validator) pkg with ozzo, for example for create_product_command it will be something like this:

``` go
type CreateProduct struct {
    ProductID   uuid.UUID 
    Name        string   
    Description string    
    Price       float64   
    CreatedAt   time.Time 
}

func NewCreateProduct(name string, description string, price float64) (*CreateProduct, error) {
    command := &CreateProduct{
        ProductID:   uuid.NewV4(),
        Name:        name,
        Description: description,
        Price:       price,
        CreatedAt:   time.Now(),
    }
    err := validator.Validate(command)
    if err != nil {
        return nil, err
    }

    return command, nil
}

// using ozzo
func (c *CreateProduct) Validate() error {
    return validation.ValidateStruct(&c,
        validation.Field(&c.ProductID, validation.Required),
        validation.Field(&c.Name, validation.Required, validation.Length(3, 255)),
        ///...
    )
}
```
If you like, feel free to contribute.

**Comment by Alan-MQ** [comment]
thank you for the tips, let me see what I can do .

**Comment by mehdihadeli** [comment]
you're wellcome :)
