### ISSUE TITLE
Upgrade package versions and Upgarde to go 21

### ISSUE THREAD

**Issue by mehdihadeli** [mehdihadeli/go-ecommerce-microservices#81]

**Comment by Alan-MQ** [comment]
in order to upgrade to go 21, we just modify go.mod at the second line to `go 1.21`?
but actually I don't have a clue about how we upgrade package versions. for all packages? including pkg/ folder? that could cause some compatiable problem right?

**Comment by mehdihadeli** [comment]
Yes, just change the version in go.mod in each service and pkg module, also for GitHub action.
Yes it is fine, maybe something like `go get -u -t -d -v ./...` for each service
