### ISSUE TITLE
Question: Introduce Service

### ISSUE THREAD

**Issue by iambudi** [mehdihadeli/go-ecommerce-microservices#85]
Hi,
Thank you so much for sharing this repo. I learn a lot and really like the way you organize the code.
I have two questions:
 
1. What if `CreateOrder (/command/create_order_handler.go)` requires aggregate action for calculating discount from third party services, or creating booking stock. Should we introduce a coordinator service on top of the command or we just execute them inside command?
2. What about the data model, should we create one for the service or we just use domain model directly?

**Comment by mehdihadeli** [comment]
Hi,
Thanks for your feedback.
1. there are multiple approach for handling this, for example passing service to as a dependency to action parameter or another approach getting data from third party in our command handler and pass it as a dependency to our action. [Here](https://github.com/ardalis/DDD-NoDuplicates) there is a good repository and possible approaches for that, also this [twitter thread](https://twitter.com/kamgrzybek/status/1280868055627763713)
2. we should have persistence ignorance domain model, it should not have any tags related to database, yes it is possible for example this is a [sample in my c# code base](https://github.com/mehdihadeli/ecommerce-microservices/blob/develop/src/Services/Catalogs/ECommerce.Services.Catalogs/Products/Models/Product.cs). But if we use gorm for example we should have separated data model with gorm tags and separated domain model with its actions
